name: lines_top_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  json_theme: ^5.0.0+5
  http: ^0.13.5
  path_provider: ^2.0.13
  page_transition: ^2.0.9
  video_player: ^2.6.0
  chewie: ^1.4.0
  firebase_auth: ^4.2.2
  photo_view: ^0.14.0
  path: ^1.8.3
  sqflite: ^2.3.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.2.4
  fl_chart: ^0.66.2
  rename_app: ^1.3.2
  # flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_launcher_icons:
#   android: true
#   image_path_android: "assets/icon/icon.png"
#   min_sdk_android: 19 # android min sdk min:16, default 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/temp/bubbles1.jpeg
    - assets/temp/bubbles2.jpeg
    - assets/temp/bubbles3.jpeg
    - assets/temp/app_bar.png
    - assets/temp/app_bar.jpg
    - assets/icon/icon.png
    - assets/theme/appainter_theme.json
    - assets/images/BlackLogo.png
    - assets/images/placeholders/grey_gradient.jpg
    - assets/temp/placeholder_video.mp4
    - assets/images/backgrounds/bg_1.jpg
    - assets/images/backgrounds/bg_2.jpg
    - assets/images/backgrounds/bg_3.jpg
    - assets/images/backgrounds/bg_4.jpg
    - assets/images/backgrounds/bg_5.jpg
    - assets/images/backgrounds/bg_6.jpg
    - assets/images/backgrounds/bg_7.jpg
    - assets/images/backgrounds/bg_8.jpg
    - assets/images/backgrounds/bg_9.jpg
    - assets/images/backgrounds/bg_10.jpg
    - assets/images/backgrounds/bg_11.jpg
    - assets/images/backgrounds/bg_12.jpg
    - assets/images/backgrounds/bg_13.jpg
    - assets/images/backgrounds/bg_14.jpg
    - assets/images/backgrounds/bg_15.jpg
    - assets/images/backgrounds/bg_16.jpg
    - assets/images/backgrounds/bg_17.jpg
    - assets/images/backgrounds/bg_18.jpg
    - assets/images/backgrounds/bg_19.jpg
    - assets/images/backgrounds/bg_20.jpg
    - assets/images/backgrounds/bg_21.jpg
    - assets/images/backgrounds/bg_22.jpg
    - assets/images/backgrounds/bg_23.jpg
    - assets/images/backgrounds/bg_24.jpg
    - assets/images/backgrounds/bg_25.jpg
    - assets/images/backgrounds/bg_26.jpg
    - assets/images/backgrounds/bg_27.jpg
    - assets/images/backgrounds/bg_28.jpg
    - assets/images/backgrounds/bg_29.jpg
    - assets/images/backgrounds/bg_30.jpg
    - assets/images/backgrounds/ex_1.jpg
    - assets/images/backgrounds/ex_2.jpg
    - assets/images/backgrounds/ex_3.jpg
    - assets/images/backgrounds/ex_4.jpg
    - assets/videos/intro1.mp4
    - assets/videos/intro2.mp4
    - assets/images/backgrounds/about_me.jpg
    - assets/content/blog_posts/post_16_0
    - assets/content/blog_posts/post_17_0
    - assets/content/blog_posts/post_18_0
    - assets/content/blog_posts/post_19_0
    - assets/content/blog_posts/post_20_0
    - assets/content/blog_posts/post_21_0
    - assets/content/programs/pr_2
    - assets/content/programs/pr_6
    - assets/content/programs/pr_7
    - assets/content/trainings/tr_10
    - assets/content/trainings/tr_11
    - assets/content/trainings/tr_12
    - assets/content/trainings/tr_13
    - assets/content/trainings/tr_15
    - assets/content/trainings/tr_27
    - assets/content/trainings/tr_33
    - assets/content/trainings/tr_38
    - assets/content/trainings/tr_48
    - assets/content/exercises/ex_1.mov
    - assets/content/exercises/ex_3.mov
    - assets/content/exercises/ex_4.mov
    - assets/content/exercises/ex_6.mov
    - assets/content/exercises/ex_7.mov
    - assets/content/exercises/ex_8.mov
    - assets/content/exercises/ex_9.mov
    - assets/content/exercises/ex_10.mov
    - assets/content/exercises/ex_11.mov
    - assets/content/exercises/ex_12.mov
    - assets/content/exercises/ex_13.mov
    - assets/content/exercises/ex_14.mov
    - assets/content/exercises/ex_15.mov
    - assets/content/exercises/ex_16.mov
    - assets/content/exercises/ex_17.mov
    - assets/content/exercises/ex_18.mov
    - assets/content/exercises/ex_20.mov
    - assets/content/exercises/ex_21.mov
    - assets/content/exercises/ex_22.mov
    - assets/content/exercises/ex_23.mov
    - assets/content/exercises/ex_24.mov
    - assets/content/exercises/ex_25.mov
    - assets/content/exercises/ex_26.mov
    - assets/content/exercises/ex_27.mov
    - assets/content/exercises/ex_28.mov
    - assets/content/exercises/ex_29.mov
    - assets/content/exercises/ex_31.mov
    - assets/content/exercises/ex_33.mov
    - assets/content/exercises/ex_34.mov
    - assets/content/exercises/ex_35.mov
    - assets/content/exercises/ex_38.mov
    - assets/content/exercises/ex_39.mov
    - assets/content/exercises/ex_40.mov
    - assets/content/exercises/ex_41.mov
    - assets/content/exercises/ex_42.mov
    - assets/content/exercises/ex_43.mov
    - assets/content/exercises/ex_44.mov
    - assets/content/exercises/ex_46.mov
    - assets/content/exercises/ex_47.mov
    - assets/content/exercises/ex_49.mov
    - assets/content/exercises/ex_51.mov
    - assets/content/exercises/ex_54.mov
    - assets/content/exercises/ex_55.mov
    - assets/content/exercises/ex_57.mov
    - assets/content/exercises/ex_58.mov
    - assets/content/exercises/ex_59.mov
    - assets/content/exercises/ex_62.mov
    - assets/content/exercises/ex_63.mov
    - assets/content/exercises/ex_64.mov
    - assets/content/exercises/ex_65.mov
    - assets/content/exercises/ex_66.mov
    - assets/content/exercises/ex_67.mov
    - assets/content/exercises/ex_68.mov
    - assets/content/exercises/ex_69.mov
    - assets/content/exercises/ex_70.mov
    - assets/content/exercises/ex_71.mov
    - assets/content/exercises/ex_72.mov
    - assets/content/exercises/ex_73.mov
    - assets/content/exercises/ex_74.mov
    - assets/content/exercises/ex_75.mov
    - assets/content/exercises/ex_76.mov
    - assets/content/exercises/ex_77.mov
    - assets/content/exercises/ex_78.mov
    - assets/content/exercises/ex_79.mov
    - assets/content/exercises/ex_80.mov
    - assets/content/exercises/ex_81.mov
    - assets/content/exercises/ex_82.mov
    - assets/content/exercises/ex_83.mov
    - assets/content/exercises/ex_84.mov
    - assets/content/exercises/ex_85.mov
    - assets/content/exercises/ex_86.mov
    - assets/content/exercises/ex_87.mov
    - assets/content/exercises/ex_88.mov
    - assets/content/exercises/ex_89.mov
    - assets/content/exercises/ex_90.mov
    - assets/content/exercises/ex_91.mov
    - assets/content/exercises/ex_92.mov
    - assets/content/exercises/ex_93.mov
    - assets/content/exercises/ex_94.mov
    - assets/content/exercises/ex_95.mov
    - assets/content/exercises/ex_96.mov
    - assets/content/exercises/ex_97.mov
    - assets/content/exercises/ex_98.mov
    - assets/content/exercises/ex_99.mov
    - assets/content/exercises/ex_100.mov
    - assets/content/exercises/ex_101.mov
    - assets/content/exercises/ex_102.mov
    - assets/content/exercises/ex_103.mov
    - assets/content/exercises/ex_104.mov
    - assets/content/exercises/ex_105.mov
    - assets/content/exercises/ex_106.mov
    - assets/content/exercises/ex_107.mov
    - assets/content/exercises/ex_108.mov
    - assets/content/exercises/ex_109.mov
    - assets/content/exercises/ex_110.mov
    - assets/content/exercises/ex_111.mov
    - assets/content/exercises/ex_112.mov
    - assets/content/exercises/ex_113.mov
    - assets/content/exercises/ex_114.mov
    - assets/content/exercises/ex_115.mov
    - assets/content/exercises/ex_116.mov
    - assets/content/exercises/ex_117.mov
    - assets/content/exercises/ex_118.mov
    - assets/content/exercises/ex_119.mov
    - assets/content/exercises/ex_120.mov
    - assets/content/blog_posts.txt
    - assets/content/exercises.txt
    - assets/content/trainings.txt
    - assets/content/programs.txt



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceSerifPro
      fonts:
        - asset: assets/fonts/SourceSerifPro-Regular.ttf
        - asset: assets/fonts/SourceSerifPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSerifPro-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
